SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE DATABSE sih;

USE sih;

CREATE TABLE `sih`.`farmer` ( `Name` INT(125) NOT NULL , `ID` BIGINT(12) NOT NULL , `BANKACCOUNT` BIGINT(20) NOT NULL , `LANDRECORD` BIGINT(20) NOT NULL , `CROP1` VARCHAR(120) NOT NULL , `CROP2` VARCHAR(120) NOT NULL , `CROP3` VARCHAR(120) NOT NULL , `CROP3` VARCHAR(120) NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB;
CREATE TABLE `sih`.`farmers` ( `Id` INT(255) NOT NULL AUTO_INCREMENT , `Name` VARCHAR(255) NOT NULL , `Aadhar` INT(12) NOT NULL , `LandRecord_no` INT(50) NOT NULL , `Bank_account_no` INT(20) NOT NULL , `Area_of_land` INT NOT NULL , `Latitude` BIGINT NOT NULL , `Longitude` BIGINT NOT NULL , `SoilType` VARCHAR(255) NOT NULL , `Mobile_no` BIGINT(10) NOT NULL , `Address` VARCHAR(255) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

CREATE TABLE `sih`.`shops` ( `ShopId` INT(10) NOT NULL AUTO_INCREMENT , `ShopName` VARCHAR(255) NOT NULL , `Address` VARCHAR(255) NOT NULL , `Contact_No` INT(10) NOT NULL , PRIMARY KEY (`ShopId`)) ENGINE = InnoDB;
CREATE TABLE `sih`.`farmers` ( `Id` BIGINT NOT NULL , `Name` VARCHAR(125) NOT NULL , `District` VARCHAR(125) NOT NULL , `Village` VARCHAR(125) NOT NULL , `LandRecordNo` BIGINT(20) NOT NULL , `LandArea` BIGINT(20) NOT NULL , `SoilType` VARCHAR(25) NOT NULL , `Latitude` FLOAT NOT NULL , `Longitude` FLOAT NOT NULL , `WaterSource` VARCHAR(120) NOT NULL , `BankAccountNo` BIGINT(20) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

